### ISSUE TITLE
Greedy Algorithm

### ISSUE THREAD

**Issue by johnblakey** [johnblakey/CS-325-Project-2#2]
Another approach to coin change problem is the greedy approach. This implementation is called change greedy. This is also “naive” since it may not be optimal.
- Use the largest value coin possible.
- Subtract the value of this coin from the amount of change to be made.
- Repeat.

**Comment by johnblakey** [comment]
See project report requirement that applies to each individual algorithm.

**Comment by TimothyBramlett** [comment]
Uploaded this one friday night.  Closing issue.
